{% set name = "pytest-gee" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_gee-{{ version }}.tar.gz
  sha256: dfe23372414bf747a45f0b66108d0f7b2e9d9315cd6aab534b0cd0a829f17b13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.14
    - earthengine-api
    - pytest
    - pytest-regressions
    - geopandas
    - pillow

test:
  imports:
    - pytest_gee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: The Python plugin for your GEE based packages.
  license: MIT
  license_file: LICENSE
  home: https://github.com/gee-community/pytest-gee

extra:
  recipe-maintainers:
    - 12rambau
