{% set name = "pytest-gee" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_gee-{{ version }}.tar.gz
  sha256: 30c1010c984533552ba74af6d19e731eed0707a8107f4ac912e8e40000084f26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - deprecated >=1.2.14
    - earthengine-api
    - pytest

test:
  imports:
    - pytest_gee
  commands:
    - pip check
  requires:
    - pip

about:
  summary: The Python plugin for your GEE based packages.
  license: MIT
  license_file: LICENSE
  home: https://github.com/gee-community/pytest-gee

extra:
  recipe-maintainers:
    - 12rambau
